# Generated by Django 5.0.14 on 2026-06-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminders', '0001_initial'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='rewards.reward'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['is_sent', 'reminder_time'], name='reminders_r_is_sent_526d92_idx'),
        ),
    ]
