# Generated by Django 5.0.14 on 2026-06-16 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_initial'),
        ('rewards', '0003_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('EXPIRY_REMINDER', 'Expiry Reminder'), ('REWARD_CREATED', 'Reward Created'), ('REWARD_USED', 'Reward Used'), ('SYSTEM', 'System')], db_index=True, default='EXPIRY_REMINDER', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reminder',
            name='offset_days',
            field=models.IntegerField(blank=True, choices=[(1, '1 Day Before'), (3, '3 Days Before'), (7, '7 Days Before')], help_text='Days before expiry this reminder is scheduled for (auto-created reminders).', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App')], default='EMAIL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('offset_days__isnull', False)), fields=('reward', 'offset_days', 'reminder_type'), name='unique_active_offset_reminder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reminders.reminder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='reminders_n_user_id_9699dd_idx'),
        ),
    ]
