# Generated by Django 5.0.14 on 2026-06-15 18:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('TRAVEL', 'Travel'), ('FOOD', 'Food'), ('SHOPPING', 'Shopping'), ('CASHBACK', 'Cashback'), ('ENTERTAINMENT', 'Entertainment'), ('BILLS', 'Bills'), ('OTHERS', 'Others')], db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('reward_type', models.CharField(choices=[('CASHBACK', 'Cashback'), ('COUPON', 'Coupon'), ('GIFT_CARD', 'Gift Card'), ('LOYALTY_POINTS', 'Loyalty Points'), ('PAYMENT_APP_REWARD', 'Payment App Reward')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('encrypted_code', models.CharField(blank=True, db_column='code', max_length=500, null=True)),
                ('encrypted_pin', models.CharField(blank=True, db_column='pin', max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('loyalty_program_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_name', models.CharField(db_index=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_starred', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('USE', 'Use'), ('RESTORE', 'Restore')], max_length=20)),
                ('change_log', models.JSONField(help_text='JSON body tracking updated fields and before/after values.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Reward Audit Log',
                'verbose_name_plural': 'Reward Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_category_name'),
        ),
        migrations.AddField(
            model_name='reward',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='rewards.category'),
        ),
    ]
