# Generated by Django 5.0.14 on 2026-06-15 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardauditlog',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='rewards.reward'),
        ),
        migrations.AddField(
            model_name='rewardauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['user', 'status'], name='rewards_rew_user_id_b5d2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['expiry_date', 'status'], name='rewards_rew_expiry__fea3ce_idx'),
        ),
    ]
