# Generated by Django 5.0.14 on 2026-06-15 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_image', models.ImageField(help_text='Uploaded image of the receipt or voucher.', upload_to='receipts/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('raw_ocr_data', models.JSONField(blank=True, help_text='Raw response JSON from the OCR engine.', null=True)),
                ('detected_text', models.TextField(blank=True, help_text='Extracted plain text lines.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Errors logged if the OCR extraction fails.', null=True)),
            ],
            options={
                'verbose_name': 'OCR Transaction',
                'verbose_name_plural': 'OCR Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
