# Generated by Django 5.0.14 on 2026-06-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocr', '0001_initial'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtransaction',
            name='processed_reward',
            field=models.OneToOneField(blank=True, help_text='The Reward object generated from this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_transaction', to='rewards.reward'),
        ),
    ]
